[snowflake]
account = "account"
user = "user"
password = "password"
warehouse = "warehouse"
database = "database"
schema = "schema"

[bigquery]
file_path='path/to/your_creds.json'
project_name = 'project_name'
connection_type = 'application_default' # `application_default` or `service_account`

[internal_db]
engine_str = "sqlite:///expanto.db"
async_engine_str = "sqlite+aiosqlite:///expanto.db"

[internal_db.connect_args]
pool_size = 5
max_overflow = 5
pool_timeout = 10
pool_recycle = 900
connect_args = { check_same_thread = false}

# Agent API Keys
[api_keys]
PROVIDER_API_KEY = "PROVIDER_API_KEY"
TAVILY_API_KEY = "TAVILY_API_KEY"
LOGFIRE_TOKEN = "LOGFIRE_TOKEN"